# Generated by Django 3.1.7 on 2021-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('company', 'Company'), ('home', 'Home'), ('teach', 'Teach'), ('army', 'Army'), ('none', 'None')], max_length=100, null=True)),
                ('haveJob', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True)),
                ('TermJob', models.CharField(choices=[('twoless', 'Twoless'), ('twomore', 'Twomore'), ('many', 'Many')], max_length=100, null=True)),
                ('ManageJob', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True)),
                ('Student', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True)),
                ('HaveLesson', models.CharField(choices=[('degree', 'Degree'), ('lifetime', 'Lifetime'), ('language', 'Language')], max_length=100, null=True)),
                ('Live', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('family', 'Family'), ('school', 'School'), ('bunker', 'Bunker')], max_length=100, null=True)),
                ('Leisure', models.CharField(choices=[('movie', 'Movie'), ('club', 'Club'), ('perform', 'Perform'), ('concert', 'Concert'), ('museum', 'Museum'), ('park', 'Park'), ('camping', 'Camping'), ('beach', 'Beach'), ('sports', 'Sports'), ('house', 'House'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('game', 'Game'), ('poll', 'Poll'), ('chess', 'Chess'), ('sns', 'Sns'), ('message', 'Message'), ('study', 'Study'), ('news', 'News'), ('cook', 'Cook'), ('drive', 'Drive'), ('spa', 'Spa'), ('job', 'Job'), ('service', 'Service')], max_length=100, null=True)),
                ('Hobby', models.CharField(choices=[('book', 'Book'), ('music', 'Music'), ('play', 'Play'), ('sing', 'Sing'), ('dance', 'Dance'), ('write', 'Write'), ('drawing', 'Drawing'), ('cook', 'Cook'), ('animal', 'Animal'), ('stock', 'Stock'), ('news', 'News'), ('magazine', 'Magazine'), ('photo', 'Photo')], max_length=100, null=True)),
                ('Sports', models.CharField(choices=[('basketball', 'Basketball'), ('baseball', 'Baseball'), ('soccer', 'Soccer'), ('football', 'Football'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('golf', 'Golf'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('pingpong', 'Pingpong'), ('swimming', 'Swimming'), ('bicycle', 'Bicycle'), ('ski', 'Ski'), ('skate', 'Skate'), ('jogging', 'Jogging'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('hiking', 'Hiking'), ('fishing', 'Fishing'), ('health', 'Health'), ('taekwondo', 'Taekwondo'), ('lesson', 'Lesson'), ('none', 'None')], max_length=100, null=True)),
                ('Rest', models.CharField(choices=[('inbusiness', 'Inbusiness'), ('outbusiness', 'Outbusiness'), ('home', 'Home'), ('intravle', 'Intravle'), ('outtravle', 'Outtravle')], max_length=100, null=True)),
            ],
        ),
    ]
