# Generated by Django 3.1.7 on 2021-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210311_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Rest',
        ),
        migrations.AddField(
            model_name='survey',
            name='Rest',
            field=models.ManyToManyField(blank=True, to='surveys.Rest'),
        ),
    ]
