# Generated by Django 3.1.7 on 2021-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210311_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='name',
            field=models.CharField(choices=[('inbusiness', 'Inbusiness'), ('outbusiness', 'Outbusiness'), ('home', 'Home'), ('intravle', 'Intravle'), ('outtravle', 'Outtravle')], max_length=100, null=True),
        ),
    ]
