# Generated by Django 3.1.7 on 2021-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20210311_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Rest',
            field=models.ManyToManyField(to='surveys.Rest'),
        ),
    ]
