# Generated by Django 3.1.7 on 2021-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20210311_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='Rest',
        ),
        migrations.AddField(
            model_name='survey',
            name='Rest',
            field=models.SlugField(choices=[('inbusiness', 'Inbusiness'), ('outbusiness', 'Outbusiness'), ('home', 'Home'), ('intravle', 'Intravle'), ('outtravle', 'Outtravle')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
    ]
