# Generated by Django 3.1.7 on 2021-03-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20210311_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='Rest',
        ),
    ]
