# Generated by Django 3.1.7 on 2021-03-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_survey_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Rest',
            field=models.SlugField(choices=[('inbusiness', 'Inbusiness'), ('outbusiness', 'Outbusiness'), ('home', 'Home'), ('intravle', 'Intravle'), ('outtravle', 'Outtravle')], max_length=100, null=True),
        ),
    ]
