# Generated by Django 3.1.7 on 2021-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20210312_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Rest',
        ),
        migrations.AddField(
            model_name='survey',
            name='Rest',
            field=models.ManyToManyField(blank=True, to='surveys.Rest'),
        ),
    ]
