# Generated by Django 3.1.7 on 2021-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20210312_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='name',
            field=models.CharField(choices=[('inbusiness', 'Inbusiness'), ('outbusiness', 'Outbusiness'), ('home', 'Home'), ('intravle', 'Intravle'), ('outtravle', 'Outtravle')], max_length=50),
        ),
    ]
