# Generated by Django 3.1.7 on 2021-03-13 12:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20210312_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Hobby',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('book', 'Book'), ('music', 'Music'), ('play', 'Play'), ('sing', 'Sing'), ('dance', 'Dance'), ('write', 'Write'), ('drawing', 'Drawing'), ('cook', 'Cook'), ('animal', 'Animal'), ('stock', 'Stock'), ('news', 'News'), ('magazine', 'Magazine'), ('photo', 'Photo')], max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Leisure',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('movie', 'Movie'), ('club', 'Club'), ('perform', 'Perform'), ('concert', 'Concert'), ('museum', 'Museum'), ('park', 'Park'), ('camping', 'Camping'), ('beach', 'Beach'), ('sports', 'Sports'), ('house', 'House'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('game', 'Game'), ('poll', 'Poll'), ('chess', 'Chess'), ('sns', 'Sns'), ('message', 'Message'), ('study', 'Study'), ('news', 'News'), ('cook', 'Cook'), ('drive', 'Drive'), ('spa', 'Spa'), ('job', 'Job'), ('service', 'Service')], max_length=140, null=True),
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Rest',
        ),
        migrations.AddField(
            model_name='survey',
            name='Rest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('inbusiness', 'Inbusiness'), ('outbusiness', 'Outbusiness'), ('home', 'Home'), ('intravle', 'Intravle'), ('outtravle', 'Outtravle')], max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Sports',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('basketball', 'Basketball'), ('baseball', 'Baseball'), ('soccer', 'Soccer'), ('football', 'Football'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('golf', 'Golf'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('pingpong', 'Pingpong'), ('swimming', 'Swimming'), ('bicycle', 'Bicycle'), ('ski', 'Ski'), ('skate', 'Skate'), ('jogging', 'Jogging'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('hiking', 'Hiking'), ('fishing', 'Fishing'), ('health', 'Health'), ('taekwondo', 'Taekwondo'), ('lesson', 'Lesson'), ('none', 'None')], max_length=184, null=True),
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
    ]
